services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: wms
      POSTGRES_PASSWORD: wms123
      POSTGRES_DB: wms
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: